### ISSUE TITLE
Add getter to get *logrus.Logger object of `salt/log`

### ISSUE THREAD

**Issue by mabdh** [odpf/salt#29]
**Is your feature request related to a problem? Please describe.**
grpc-middleware has support of logrus logger. However, they only accept argument with type `*logrus.Logger`. In salt, `*logrus.Logger` is private, we need to have a getter function to get the object.

**Describe the solution you'd like**
In this [file](https://github.com/odpf/salt/blob/main/log/logrus.go), we could add a new function
```
func (l *Logrus) LogrusLogger() *logrus.Logger {
	return l.log
}
```

**Comment by rahmatrhd** [comment]
what if we also add a similar getter method in the `Logger` interface that returns `interface{}`. The user can cast it to the specific logger instance that they're using either it is logrus, zap, or anything else.

**Comment by mabdh** [comment]
@rahmatrhd I was also thinking that approach as the alternative but returning interface in interface does not looks solid to me personally. But if everybody is okay with that, it is fine.

**Comment by rohilsurana** [comment]
For this specific case `*logrus.Entry` might suffice. 

But for a larger discussion I think we should instead go for more of an injecting approach, where we can inject our own `logrus.Logger` instance if needed to initialise. We could use an option for doing this, like - 
```
func LogrusWithLogger(logger *logrus.Logger) Option
```

This allows us to apply our defaults/options onto the logger as well as keep an handle of it to use it elsewhere or even modify its properties.

We could follow same pattern for other loggers for a similar looking API for all loggers.

**Comment by rohilsurana** [comment]
We keep a pointer to the injected `logrus.Logger` on our side and use it.

**Comment by mabdh** [comment]
@rohilsurana i see, sounds good. should we do that approach for now (for logrus only) ?
